services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_container
    env_file:
      - .env
    volumes:
      - ../:/workspace:cached 
    command: sleep infinity